### ISSUE TITLE
Create Endpoint: Branch

### ISSUE THREAD

**Issue by Okjonas** [effortless-mgmt/EffortlessBackend#8]
See https://docs.google.com/spreadsheets/d/1FizsXuuZQu_umTJk3J2-dmQuq3ljFgT1Sp4jrjr_zaU/edit#gid=0 for more details.

Create an endpoint for the table `Branch` with full CRUD operations.

Fields:

- ID (P-Number number of the company)
- Name
- AddressId (foreign key, address)
- ContactId (foreign key, user)
- Company

**Comment by algorythm** [comment]
Refactored to `Department`.
